java_library(
    name = "annotations",
    srcs = glob([
        "*.java",
        "test_base/*.java"
         ]),
    visibility = ["//visibility:public"],
    deps = ["@maven//:org_junit_jupiter_junit_jupiter_api",
            "@maven//:org_junit_jupiter_junit_jupiter_params",]
)