java_library(
    name = "service",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/model:model",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_runner",
        "@maven//:com_squareup_okhttp3_okhttp",
        "@maven//:com_googlecode_json_simple_json_simple"
    ]
)