java_library(
    name = "extensions",
    srcs = glob(["*.java"]),
    visibility = ["//src/test/java:__pkg__",
                  "//src/test/java/test/solutions_tests:__pkg__"],
    deps = ["//src/test/java/test/annotations:annotations",
            "@maven//:org_junit_jupiter_junit_jupiter_api",]
)